
server.port: 7003
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
logging:
    level:
      root: INFO
      felipe: DEBUG
spring:
    autoconfigure:
      exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration



---

spring:
    config:
        activate:
            on-profile: docker


server:
    port: 8080 


spring.datasource:
    url: jdbc:mysql://mysql/review-db
