server.port: 7000

app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003

api:
    common:
        version: 1.0.0
        title: Sample API
        description: Description of the API...
        termsOfService: MY TERMS OF SERVICE
        license: MY LICENSE
        licenseUrl: MY LICENSE URL
        externalDocDesc: MY WIKI PAGE
        externalDocUrl: MY WIKI URL
        contact:
            name: NAME OF CONTACT
            url: URL TO CONTACT
            email: contact@mail.com
springdoc:
    swagger-ui.path: /openapi/swagger-ui.html
    api-docs.path: /openapi/v3/api-docs
    packagesToScan: felipe.microservice.composite.product
    pathsToMatch: /**

---
spring.config.activate.on-profile: docker

server.port: 8080

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080
